### ISSUE TITLE
Compatible .NET framework version

### ISSUE THREAD

**Issue by rbagdona** [ap0llo/markdown-generator#78]
When trying to install using .NET Framework 4.5.1, I am getting an error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Grynwald.MarkdownGenerator 2.5.34'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				
`

However, when I try installing it on 4.7.2 version, it works just fine. 
Would it be possible to specify the compatible version?

**Comment by ap0llo** [comment]
The library targets `netstandard2.0` which is considered the least common denominator for most libraries.
It supports both .NET Core and .NET Framework, all the way back to .NET Framework 4.6.1 (see [.NET implementation support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)).

Considering .NET Framework 4.5.1 is 7 years old by now and newer framework versions are supported on all [Windows versions back to Windows 7](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements), I don't really see any benefit in supporting frameworks that do not support `netstandard2.0`.
